# Generated by Django 5.0 on 2023-12-25 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_button', models.CharField(max_length=100, verbose_name='Тип кнопки')),
            ],
            options={
                'verbose_name': 'Кнопка',
                'verbose_name_plural': 'Кнопки',
            },
        ),
        migrations.CreateModel(
            name='AddSingleCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files', verbose_name='Файл для креатива')),
                ('link', models.CharField(max_length=500, verbose_name='Ссылка')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creatives.typebutton', verbose_name='Тип кнопки')),
            ],
            options={
                'verbose_name': 'Креатив',
                'verbose_name_plural': 'Креативы',
            },
        ),
        migrations.CreateModel(
            name='AddDoubleCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_file', models.FileField(upload_to='files', verbose_name='Первый файл для креатива')),
                ('first_link', models.CharField(max_length=500, verbose_name='Первая ссылка')),
                ('first_name', models.CharField(max_length=200, verbose_name='Первое название')),
                ('second_file', models.FileField(upload_to='files', verbose_name='Второй файл для креатива')),
                ('second_link', models.CharField(max_length=500, verbose_name='Вторая ссылка')),
                ('second_name', models.CharField(max_length=200, verbose_name='Второе название')),
                ('button', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creatives.typebutton', verbose_name='Тип кнопки')),
            ],
            options={
                'verbose_name': 'Двойной креатив',
                'verbose_name_plural': 'Двойные креативы',
            },
        ),
    ]
