# Generated by Django 5.0 on 2023-12-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddoublecreative',
            name='first_file',
        ),
        migrations.RemoveField(
            model_name='adddoublecreative',
            name='second_file',
        ),
        migrations.RemoveField(
            model_name='addsinglecreative',
            name='file',
        ),
    ]
