# Generated by Django 5.0 on 2023-12-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0002_remove_adddoublecreative_first_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleStickerCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_of_story_first', models.URLField(verbose_name='Ссылка на историю №1')),
                ('link_of_story_second', models.URLField(verbose_name='Ссылка на историю №2')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Двойная ссылка-стикер',
                'verbose_name_plural': 'Двойные ссылка-стикеры',
            },
        ),
        migrations.CreateModel(
            name='RepostCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_of_story', models.URLField(verbose_name='Ссылка на историю')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Репост',
                'verbose_name_plural': 'Репосты',
            },
        ),
        migrations.CreateModel(
            name='StickerCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_of_story', models.URLField(verbose_name='Ссылка на историю')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Ссылка-стикер',
                'verbose_name_plural': 'Ссылка-стикеры',
            },
        ),
    ]
