# Generated by Django 5.0 on 2023-12-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0003_doublestickercreative_repostcreative_stickercreative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doublestickercreative',
            name='link_of_story_first',
            field=models.CharField(max_length=150, verbose_name='Ссылка на историю №1'),
        ),
        migrations.AlterField(
            model_name='doublestickercreative',
            name='link_of_story_second',
            field=models.CharField(max_length=150, verbose_name='Ссылка на историю №2'),
        ),
        migrations.AlterField(
            model_name='repostcreative',
            name='link_of_story',
            field=models.CharField(max_length=150, verbose_name='Ссылка на историю'),
        ),
        migrations.AlterField(
            model_name='stickercreative',
            name='link_of_story',
            field=models.CharField(max_length=150, verbose_name='Ссылка на историю'),
        ),
    ]
