# Generated by Django 5.0 on 2024-01-07 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0005_statuscreative'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddoublecreative',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='creatives.statuscreative', verbose_name='Статус проверки'),
        ),
        migrations.AddField(
            model_name='addsinglecreative',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='creatives.statuscreative', verbose_name='Статус проверки'),
        ),
        migrations.AddField(
            model_name='doublestickercreative',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='creatives.statuscreative', verbose_name='Статус проверки'),
        ),
        migrations.AddField(
            model_name='repostcreative',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='creatives.statuscreative', verbose_name='Статус проверки'),
        ),
        migrations.AddField(
            model_name='stickercreative',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='creatives.statuscreative', verbose_name='Статус проверки'),
        ),
    ]
