# Generated by Django 5.0 on 2024-01-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0006_adddoublecreative_status_addsinglecreative_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddoublecreative',
            name='first_file',
            field=models.FileField(null=True, upload_to='files', verbose_name='Первый файл для креатива'),
        ),
        migrations.AddField(
            model_name='adddoublecreative',
            name='second_file',
            field=models.FileField(null=True, upload_to='files', verbose_name='Второй файл для креатива'),
        ),
        migrations.AddField(
            model_name='addsinglecreative',
            name='file',
            field=models.FileField(null=True, upload_to='files', verbose_name='Файл для креатива'),
        ),
    ]
