# Generated by Django 5.0 on 2024-02-06 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0008_adddoublecreative_user_addsinglecreative_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddoublecreative',
            name='button',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='creatives.typebutton', verbose_name='Тип кнопки'),
        ),
        migrations.AlterField(
            model_name='addsinglecreative',
            name='button',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='creatives.typebutton', verbose_name='Тип кнопки'),
        ),
    ]
