# Generated by Django 5.0 on 2024-02-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0009_alter_adddoublecreative_button_and_more'),
        ('reservation', '0003_delete_creativemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='addsinglecreative',
            name='reservation',
            field=models.ManyToManyField(blank=True, null=True, to='reservation.dateofreservation', verbose_name='Бронирование'),
        ),
    ]
