# Generated by Django 5.0 on 2024-02-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0011_addsinglecreative_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddoublecreative',
            name='creative_type',
            field=models.CharField(default='AddDoubleCreative', max_length=100, verbose_name='Тип креатива'),
        ),
        migrations.AddField(
            model_name='addsinglecreative',
            name='creative_type',
            field=models.CharField(default='AddSingleCreative', max_length=100, verbose_name='Тип креатива'),
        ),
        migrations.AddField(
            model_name='doublestickercreative',
            name='creative_type',
            field=models.CharField(default='DoubleStickerCreative', max_length=100, verbose_name='Тип креатива'),
        ),
        migrations.AddField(
            model_name='repostcreative',
            name='creative_type',
            field=models.CharField(default='RepostCreative', max_length=100, verbose_name='Тип креатива'),
        ),
        migrations.AddField(
            model_name='stickercreative',
            name='creative_type',
            field=models.CharField(default='StickerCreative', max_length=100, verbose_name='Тип креатива'),
        ),
    ]
