# Generated by Django 5.0 on 2024-02-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creatives', '0013_adddoublecreative_archive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddoublecreative',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата добавления креатива'),
        ),
        migrations.AddField(
            model_name='doublestickercreative',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата добавления креатива'),
        ),
        migrations.AddField(
            model_name='repostcreative',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата добавления креатива'),
        ),
        migrations.AddField(
            model_name='stickercreative',
            name='date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата добавления креатива'),
        ),
    ]
