# Generated by Django 5.0 on 2024-01-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта пользователя')),
                ('account_vk', models.CharField(max_length=150, verbose_name='VK ID пользователя')),
            ],
            options={
                'verbose_name': 'Пользователь для теста',
                'verbose_name_plural': 'Пользователи для теста',
            },
        ),
    ]
