# Generated by Django 5.0 on 2023-12-29 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название настройки')),
            ],
            options={
                'verbose_name': 'Вид настройки',
                'verbose_name_plural': 'Виды настроек',
            },
        ),
        migrations.CreateModel(
            name='CommunitySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_telegram', models.URLField(blank=True, null=True, verbose_name='Ссылка на телеграм канал')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.communitymodel', verbose_name='Сообщество')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.setting', verbose_name='Вид настройки')),
            ],
            options={
                'verbose_name': 'Настройки сообщества',
                'verbose_name_plural': 'Настройки сообществ',
            },
        ),
    ]
