# Generated by Django 5.0 on 2024-01-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_setting_communitysetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusCommunities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='Статус проверки')),
            ],
            options={
                'verbose_name': 'Статус проверки сообщества',
                'verbose_name_plural': 'Статусы проверки сообществ',
            },
        ),
    ]
