# Generated by Django 5.0 on 2024-01-07 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_statuscommunities'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymodel',
            name='status_of_check',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='communities.statuscommunities', verbose_name='Статус'),
        ),
    ]
