# Generated by Django 5.0 on 2024-02-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_communitymodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymodel',
            name='name',
            field=models.CharField(max_length=350, verbose_name='Имя сообщества'),
        ),
    ]
