# Generated by Django 5.0 on 2024-02-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_alter_communitymodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitymodel',
            name='photo',
        ),
    ]
