# Generated by Django 5.0 on 2024-02-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_remove_communitymodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuscommunities',
            name='status',
            field=models.CharField(max_length=300, verbose_name='Статус проверки'),
        ),
    ]
