# Generated by Django 5.0 on 2024-02-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0009_communitymodel_name_id_commission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitymodel',
            name='url_commission',
            field=models.URLField(blank=True, default='https://www.shopify.com/blog/low-investment-business-ideas', verbose_name='Ссылка которая должна быть в сообществе'),
        ),
    ]
