# Generated by Django 5.0 on 2024-02-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0010_alter_communitymodel_url_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitymodel',
            name='name_id_commission',
        ),
    ]
