# Generated by Django 5.0 on 2024-02-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0011_remove_communitymodel_name_id_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
