# Generated by Django 5.0 on 2024-02-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0012_communitymodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymodel',
            name='count_members',
            field=models.PositiveIntegerField(null=True, verbose_name='Количество подписчиков'),
        ),
    ]
