# Generated by Django 5.0 on 2024-01-27 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_commission',
            field=models.BooleanField(default=False, verbose_name='Статус пониженной комиссии'),
        ),
    ]
