# Generated by Django 5.0 on 2024-02-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_status_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logged_in_with_new_device',
            field=models.BooleanField(default=False),
        ),
    ]
