# Generated by Django 5.0 on 2024-02-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_community_count_user_creative_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='statu_client',
            field=models.BooleanField(default=False, verbose_name='Статус заказчика'),
        ),
        migrations.AddField(
            model_name='user',
            name='status_owner',
            field=models.BooleanField(default=False, verbose_name='Статус владельца'),
        ),
    ]
