# Generated by Django 5.0 on 2024-02-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_statu_client_user_status_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vk_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='VK id в виде чисел'),
        ),
    ]
