# Generated by Django 5.0 on 2024-02-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_vk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vk_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='VK id в виде чисел'),
        ),
    ]
