# Generated by Django 5.0 on 2024-03-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='count_of_visit',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество посещений на сайте'),
        ),
    ]
