# Generated by Django 5.0 on 2024-05-26 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_vk_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='UID',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='UID пользователя'),
        ),
    ]
