# Generated by Django 5.0 on 2024-05-26 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UID',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='UID пользователя'),
        ),
    ]
