# Generated by Django 5.0 on 2024-02-08 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_creativemodel_commentary_creativemodel_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreativeModel',
        ),
    ]
