# Generated by Django 5.0 on 2023-12-20 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя пользователя')),
                ('status', models.BooleanField(default=False, verbose_name='Статус пониженной комиссии')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='PublicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя сообщества')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка группы')),
                ('status', models.BooleanField(default=False, verbose_name='Статус ссылки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commission.usermodel')),
            ],
            options={
                'verbose_name': 'Сообщество',
                'verbose_name_plural': 'Сообщества',
            },
        ),
    ]
