# Generated by Django 5.0 on 2024-01-27 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='publicmodel',
            name='name',
            field=models.CharField(max_length=150, verbose_name='ID сообщества'),
        ),
        migrations.AlterField(
            model_name='publicmodel',
            name='url',
            field=models.URLField(unique=True, verbose_name='Ссылка которая должна быть в сообществе'),
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
