# Generated by Django 5.0 on 2024-02-04 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commission', '0002_alter_publicmodel_user_alter_publicmodel_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublicModel',
        ),
    ]
