# Generated by Django 5.0 on 2024-01-22 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAdminCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_add_community', models.CharField(blank=True, max_length=500, verbose_name='Текст ошибки при добавлении сообщества')),
                ('repeat_download_text', models.CharField(blank=True, max_length=500, verbose_name='Комментарий на повторую загрузку')),
                ('erroe_cansel_story', models.CharField(blank=True, max_length=500, verbose_name='Ошибка в случае отсутствия прав на публикацию')),
                ('success_text', models.CharField(blank=True, max_length=500, verbose_name='сообщение в случае успеха')),
                ('delete_comment_text', models.CharField(blank=True, max_length=500, verbose_name='сообщение в случае удаления сообщества')),
                ('error_tg', models.CharField(blank=True, max_length=500, verbose_name='сообщение в случае ошибки с тг каналом')),
            ],
            options={
                'verbose_name': 'Настройка контента в разделе админов',
                'verbose_name_plural': 'Настройки контента в разделе админ',
            },
        ),
        migrations.CreateModel(
            name='ContentAdminHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_main_text', models.CharField(blank=True, max_length=500, verbose_name='Главный верхний текст')),
                ('main_image', models.ImageField(blank=True, upload_to='', verbose_name='Главное верхнее изображение')),
                ('second_main_text', models.CharField(blank=True, max_length=500, verbose_name='Главный текст')),
                ('second_full_text', models.TextField(blank=True, verbose_name='Основной текст в середине')),
                ('second_main_image', models.ImageField(blank=True, upload_to='', verbose_name='Главное верхнее изображение')),
                ('third_main_text', models.CharField(blank=True, max_length=500, verbose_name='Главный текст')),
                ('third_full_text', models.TextField(blank=True, verbose_name='Основной текст в третий части')),
                ('MCA_creative_text', models.CharField(blank=True, max_length=500, verbose_name='Главный текст МЦА')),
                ('MCA_creative_one', models.ImageField(blank=True, upload_to='', verbose_name='Креатив МЦА №1')),
                ('MCA_creative_two', models.ImageField(blank=True, upload_to='', verbose_name='Креатив МЦА №2')),
                ('MCA_creative_three', models.ImageField(blank=True, upload_to='', verbose_name='Креатив МЦА №3')),
                ('ZHCA_creative_text', models.CharField(blank=True, max_length=500, verbose_name='Главный текст ЖЦА')),
                ('ZHCA_creative_one', models.ImageField(blank=True, upload_to='', verbose_name='Креатив ЖЦА №1')),
                ('ZHCA_creative_two', models.ImageField(blank=True, upload_to='', verbose_name='Креатив ЖЦА №2')),
                ('ZHCA_creative_three', models.ImageField(blank=True, upload_to='', verbose_name='Креатив ЖЦА №3')),
                ('SCA_creative_text', models.CharField(blank=True, max_length=500, verbose_name='Главный текст СЦА')),
                ('SCA_creative_one', models.ImageField(blank=True, upload_to='', verbose_name='Креатив СЦА №1')),
                ('SCA_creative_two', models.ImageField(blank=True, upload_to='', verbose_name='Креатив СЦА №2')),
                ('SCA_creative_three', models.ImageField(blank=True, upload_to='', verbose_name='Креатив СЦА №3')),
                ('four_main_text', models.CharField(blank=True, max_length=500, verbose_name='Главный текст')),
                ('four_full_text', models.TextField(blank=True, verbose_name='Основной текст в третий части')),
                ('five_main_text', models.CharField(blank=True, max_length=500, verbose_name='Главный текст')),
                ('five_full_text', models.TextField(blank=True, verbose_name='Основной текст в третий части')),
            ],
            options={
                'verbose_name': 'Настройка контента в разделе админов',
                'verbose_name_plural': 'Настройки контента в разделе админ',
            },
        ),
        migrations.CreateModel(
            name='ContentAdminHelpIncrease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increase_main_text', models.CharField(blank=True, max_length=500, verbose_name='Название совета')),
                ('increase_full_text', models.CharField(blank=True, max_length=500, verbose_name='Содержание совета')),
            ],
            options={
                'verbose_name': 'Настройка контента в разделе админов (доп)',
                'verbose_name_plural': 'Настройки контента в разделе админ (доп)',
            },
        ),
        migrations.CreateModel(
            name='ContentAdminHelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_text', models.CharField(blank=True, max_length=500, verbose_name='Требование')),
            ],
            options={
                'verbose_name': 'Настройка контента в разделе админов (доп)',
                'verbose_name_plural': 'Настройки контента в разделе админ (доп)',
            },
        ),
        migrations.CreateModel(
            name='ContentAdminStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_comment_text', models.CharField(blank=True, max_length=500, verbose_name='Первый комментарий в разделе статистика')),
                ('income_comment_text', models.CharField(blank=True, max_length=500, verbose_name='Комментарий к заработку в разделе статистика')),
            ],
            options={
                'verbose_name': 'Настройка контента в разделе админов',
                'verbose_name_plural': 'Настройки контента в разделе админ',
            },
        ),
        migrations.CreateModel(
            name='ContentAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_login_pass', models.CharField(blank=True, max_length=500, verbose_name='Текст ошибка в логине или пароле')),
                ('confirmation_login', models.CharField(blank=True, max_length=500, verbose_name='Текст при подтверждении входа')),
                ('error_false_confirmation_login', models.CharField(blank=True, max_length=500, verbose_name='Текст ошибки при подтверждении входа')),
                ('message_successful', models.CharField(blank=True, max_length=500, verbose_name='Текст успешного восстановления')),
                ('message_successful_image', models.ImageField(upload_to='', verbose_name='Иконка')),
                ('message_successful_button', models.CharField(blank=True, max_length=500, verbose_name='Текст кнопки успешного восстановления')),
                ('message_error', models.CharField(blank=True, max_length=500, verbose_name='Текст неудачной привязки')),
                ('message_error_image', models.ImageField(upload_to='', verbose_name='Иконка')),
                ('message_error_button', models.CharField(blank=True, max_length=500, verbose_name='Текст кнопки неудачной привязки восстановления')),
                ('error_change_pass', models.CharField(blank=True, max_length=500, verbose_name='Текст ошибки при смене пароля')),
            ],
            options={
                'verbose_name': 'Настройка авторизации',
                'verbose_name_plural': 'Настройки авторизации',
            },
        ),
        migrations.CreateModel(
            name='ContentClientCreative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CTR_help_text', models.CharField(blank=True, max_length=500, verbose_name='Текст в подсказке CTR')),
                ('act_creative_text', models.CharField(blank=True, max_length=500, verbose_name='Текст действия с креативом')),
                ('delete_creative_text', models.CharField(blank=True, max_length=500, verbose_name='Текст при удалении креатива')),
                ('success_add_creative_text', models.CharField(blank=True, max_length=500, verbose_name='Текст успешном добавлении креатива')),
                ('error_search_story_text', models.CharField(blank=True, max_length=500, verbose_name='Текст в случае, если история не будет найдена')),
            ],
            options={
                'verbose_name': 'Настройка контента в разделе заказчиков',
                'verbose_name_plural': 'Настройки контента в разделе заказчиков',
            },
        ),
        migrations.CreateModel(
            name='ContentClientHelp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_main_text', models.CharField(blank=True, max_length=500, verbose_name='Главный верхний текст')),
                ('main_image', models.ImageField(blank=True, upload_to='', verbose_name='Главное верхнее изображение')),
                ('second_main_text', models.CharField(blank=True, max_length=500, verbose_name='Главный верхний текст')),
                ('second_full_text', models.TextField(blank=True, verbose_name='Основной текст в середине')),
                ('third_main_text', models.CharField(blank=True, max_length=500, verbose_name='Главный текст в третий части')),
                ('third_full_text', models.TextField(blank=True, verbose_name='Основной текст в третий части')),
                ('last_main_text', models.CharField(blank=True, max_length=500, verbose_name='Главный последний текст')),
                ('last_full_text', models.TextField(blank=True, verbose_name='Основной последний текст')),
            ],
            options={
                'verbose_name': 'Настройка контента в разделе заказчиков',
                'verbose_name_plural': 'Настройки контента в разделе заказчиков',
            },
        ),
        migrations.CreateModel(
            name='ContentClientReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text_panel', models.CharField(blank=True, max_length=500, verbose_name='Главный текст в рамке')),
                ('main_image_panel', models.ImageField(blank=True, upload_to='', verbose_name='Главное изображение в рамке')),
                ('thanks_text', models.CharField(blank=True, max_length=500, verbose_name='Текст благодарности')),
                ('refill_main_text', models.CharField(blank=True, max_length=500, verbose_name='Главный текст в рамке пополнения')),
                ('refill_full_text', models.TextField(blank=True, verbose_name='Основной текст пополнения')),
                ('refill_image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение в рамке "Пополнение"')),
                ('refill_help_text', models.CharField(blank=True, max_length=500, verbose_name='Текст подсказки')),
                ('error_cansel_reservation', models.CharField(blank=True, max_length=500, verbose_name='Текст в случае ошибки при отмене брони')),
                ('success_cansel_reservation', models.CharField(blank=True, max_length=500, verbose_name='Текст в случае успеха при отмене брони')),
            ],
            options={
                'verbose_name': 'Настройка контента в разделе заказчиков',
                'verbose_name_plural': 'Настройки контента в разделе заказчиков',
            },
        ),
        migrations.CreateModel(
            name='ContentFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='', verbose_name='Лого шапки')),
                ('all_rights', models.CharField(blank=True, max_length=500, verbose_name='Текст "Все права защищены"')),
                ('terms_of_use_first', models.URLField(verbose_name='Ссылка на правила пользования')),
                ('terms_of_use_second', models.URLField(verbose_name='Ссылка на пользовательское соглашение')),
            ],
            options={
                'verbose_name': 'Настройка контента футера',
                'verbose_name_plural': 'Настройки контента футера',
            },
        ),
        migrations.CreateModel(
            name='ContentHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='', verbose_name='Лого шапки')),
            ],
            options={
                'verbose_name': 'Настройка контента шапки',
                'verbose_name_plural': 'Настройки контента шапки',
            },
        ),
        migrations.CreateModel(
            name='ContentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_change_email', models.CharField(blank=True, max_length=500, verbose_name='Текст ошибки подтверждения почты')),
                ('success_change_email', models.CharField(blank=True, max_length=500, verbose_name='Текст ответа на успешное изменение почты')),
                ('success_change_email_icon', models.ImageField(blank=True, upload_to='', verbose_name='иконка в ответе на успешное изменение почты')),
                ('comment_refill', models.CharField(blank=True, max_length=500, verbose_name="Комментарий в разделе 'пополнение'")),
                ('error_refill', models.CharField(blank=True, max_length=500, verbose_name='Ошибка с платежом (пополнение)')),
                ('error_withdrawal', models.CharField(blank=True, max_length=500, verbose_name='Ошибка с платежом (вывод денег)')),
                ('error_false_confirmation_code', models.CharField(blank=True, max_length=500, verbose_name='Ошибка с подтверждением кода')),
                ('error_pass_mismatch', models.CharField(blank=True, max_length=500, verbose_name='Ошибка с несовпадением паролей')),
                ('error_pass_small', models.CharField(blank=True, max_length=500, verbose_name='Ошибка с некорректным паролем')),
            ],
        ),
        migrations.CreateModel(
            name='ContentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_repeat_pass', models.CharField(blank=True, max_length=500, verbose_name='Текст ошибки с эл.почтой')),
                ('error_false_pass', models.CharField(blank=True, max_length=500, verbose_name='Текст ошибки с паролем')),
                ('error_confirmation_email', models.CharField(blank=True, max_length=500, verbose_name='Текст ошибки при подтверждение почты')),
            ],
            options={
                'verbose_name': 'Настройка регистрации',
                'verbose_name_plural': 'Настройки регистрации',
            },
        ),
        migrations.CreateModel(
            name='ContentSpecialCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_text', models.CharField(blank=True, max_length=500, verbose_name='Текст главного раздела')),
                ('help_text', models.CharField(blank=True, max_length=500, verbose_name='Текст в рамке')),
                ('help_image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение в рамке')),
                ('error', models.CharField(blank=True, max_length=500, verbose_name='Текст в случае ошибки или неудачи')),
                ('success', models.CharField(blank=True, max_length=500, verbose_name='Текст в случае успешной проверки')),
            ],
            options={
                'verbose_name': 'Настройка контента пониженной комисии',
                'verbose_name_plural': 'Настройки контента пониженной комисии',
            },
        ),
        migrations.CreateModel(
            name='TypeLending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название лендинга')),
            ],
            options={
                'verbose_name': 'Тип лендинга',
                'verbose_name_plural': 'Типы лендинга',
            },
        ),
        migrations.CreateModel(
            name='TypeReferralSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Тип реферальной системы (для кого)')),
            ],
            options={
                'verbose_name': 'Тип реферальной системы',
                'verbose_name_plural': 'Типы реферальной системы',
            },
        ),
        migrations.CreateModel(
            name='TypeTechnicalSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Тип поддержки (для кого)')),
            ],
            options={
                'verbose_name': 'Тип поддержки',
                'verbose_name_plural': 'Типы поддержки',
            },
        ),
        migrations.CreateModel(
            name='QuestionContentLendingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('type_lending', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.typelending', verbose_name='К какому лендингу относится')),
            ],
            options={
                'verbose_name': 'Лендинг (Вопрос)',
            },
        ),
        migrations.CreateModel(
            name='PositiveContentLendingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст преимущества')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение преимущества')),
                ('type_lending', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.typelending', verbose_name='К какому лендингу относится')),
            ],
            options={
                'verbose_name': 'Лендинг (Преимущество)',
            },
        ),
        migrations.CreateModel(
            name='ContentLendingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_text_bold', models.CharField(blank=True, max_length=500, verbose_name='Главный текст в первой рамке')),
                ('first_text_small', models.CharField(blank=True, max_length=500, verbose_name='Второстепенный текст в первой рамке')),
                ('first_image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение в первой рамке')),
                ('second_main_text', models.CharField(blank=True, max_length=500, verbose_name='Текст во второй рамке')),
                ('author_text', models.CharField(blank=True, max_length=500, verbose_name='Автор текст')),
                ('second_image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение во второй рамке')),
                ('community_main_text', models.CharField(blank=True, max_length=500, verbose_name='Главный текст в разделе сообществ')),
                ('community_count', models.PositiveIntegerField(default=0, verbose_name='Количество сообществ')),
                ('creative_main_text', models.CharField(blank=True, max_length=500, verbose_name='Главный текст раздела')),
                ('creative_one', models.ImageField(blank=True, upload_to='', verbose_name='Креатив №1')),
                ('creative_two', models.ImageField(blank=True, upload_to='', verbose_name='Креатив №2')),
                ('creative_three', models.ImageField(blank=True, upload_to='', verbose_name='Креатив №3')),
                ('third_text_bold', models.CharField(blank=True, max_length=500, verbose_name='Главный текст в третьей рамке')),
                ('third_text_small', models.CharField(blank=True, max_length=500, verbose_name='Второстепенный текст в третьей рамке')),
                ('third_image', models.ImageField(blank=True, upload_to='', verbose_name='Изображение в третьей рамке')),
                ('vk_main_text', models.CharField(blank=True, max_length=500, verbose_name='Главный текст в рамке vk')),
                ('vk_second_text', models.CharField(blank=True, max_length=500, verbose_name='Второстепенный текст в рамке vk')),
                ('vk_link', models.URLField(blank=True, verbose_name='Ссылка на vk')),
                ('type_lending', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.typelending', verbose_name='Вид лендинга')),
            ],
            options={
                'verbose_name': 'Лендинг',
            },
        ),
        migrations.CreateModel(
            name='ContentReferralSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Основной текст в разделе')),
                ('first_icon', models.ImageField(blank=True, upload_to='', verbose_name='Первая иконка')),
                ('second_icon', models.ImageField(blank=True, upload_to='', verbose_name='Вторая иконка')),
                ('main_image', models.ImageField(blank=True, upload_to='', verbose_name='Основное изображение')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.typereferralsystem', verbose_name='К какому типу относятся настройки')),
            ],
            options={
                'verbose_name': 'Настройка контента реферальной системы',
                'verbose_name_plural': 'Настройки контента реферальной системы',
            },
        ),
        migrations.CreateModel(
            name='ContentTechnicalSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Цитата')),
                ('author', models.CharField(blank=True, max_length=150, verbose_name='Автор цитаты')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка на техподдержку VK')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='content.typetechnicalsupport', verbose_name='К какому типу относятся настройки')),
            ],
            options={
                'verbose_name': 'Настройка контента техподдержка',
                'verbose_name_plural': 'Настройки контента техподдержка',
            },
        ),
    ]
